name: Deploy on S3

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with: # ruby version is inferred from `.ruby-version
          ruby-version: 2.7
      - run: ruby --version
      - name: Install dependencies
        run: |
          bundle config set --local without 'development'
          bundle install --jobs 4 --retry 3
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - run: bundle exec middleman build --verbose
      - name: Publish to S3
        run: bundle exec middleman s3_sync
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: eu-central-1
          AWS_BUCKET: www.be-oi.be
